### PR TITLE
master -> main

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Comment by RyanZim** [comment]
I agree this should be changed, since `master` isn't universal anymore; not sure if "default" is the word we want, though.

**Comment by larshp** [comment]
yea, true, better suggestions welcome 😄

**Comment by strugee** [comment]
"Separate/secondary", perhaps?

**Comment by andylolz** [comment]
Agree "default" could be confusing here (since some other branch might be the default one.)

I suggest `main`, given that seems to be the go-to replacement.

**Comment by larshp** [comment]
changed to "main"

**Review by RyanZim — APPROVED** [review]

**Pull request merged**
